development:
  db:
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
    name: <%= ENV['DB_NAME'] %>
    pool: 5
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
  redis:
    url: ENV['REDIS_URL']
  sftp:
    host: ENV['SFTP_HOST']
    port: 23
    password: pass
    user: foo
    remote_path: upload/
    local_path: tmp/
# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
production:
  db:
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
    name: <%= ENV['DB_NAME'] %>
    pool: 5
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
  fcm_server_key: <%= ENV['FCM_SERVER_KEY'] %> 
  redis:
    url: <%= ENV['REDIS_URL'] %> 
  sftp:
    host: <%= ENV['SFTP_HOST'] %> 
    port: <%= ENV['SFTP_PORT'] %> 
    password:  <%= ENV['SFTP_PASS'] %> 
    user:  <%= ENV['SFTP_USER'] %> 
    remote_path: upload/
    local_path: tmp/

